### ISSUE TITLE
The use of duplicate icons for different purposes is confusing.

### ISSUE THREAD

**Issue by egladman** [CWDG/cwdg-website#104]
The officers' icon link and the "who we are" section  use the same  icon. I suggest changing the icon for the "who we are" section. It is rather confusing.

**Comment by J3RN** [comment]
This makes sense. That said, the "About Page" is sort of longing for some purpose for existence, so it may be worthy of removing altogether, and being replaced with something more worthwhile. Resources, maybe.

**Comment by J3RN** [comment]
Closing in deference to #113
