### ISSUE TITLE
Mobile View

### ISSUE THREAD

**Issue by J3RN** [CWDG/cwdg-website#24]
The site doesn't look so hot on mobile. I'm thinking about using Bourbon's Neat to do some responsive design and media queries.

Thoughts?

**Comment by J3RN** [comment]
Alright, I only have 2 remaining gripes.

These list items aren't lined up
![screenshot_2015-01-20-12-14-24](https://cloud.githubusercontent.com/assets/2058614/5822026/7a29fb4a-a09e-11e4-88d0-df75791fd494.png)

There should be a little left padding on these
![screenshot_2015-01-20-12-14-31](https://cloud.githubusercontent.com/assets/2058614/5822009/6272856c-a09e-11e4-81ba-64413ef7df0a.png)

**Comment by tarebyte** [comment]
Also this is now happening for screens the size of an iPhone 5 or smaller.

![ios simulator screen shot feb 4 2015 5 10 05 pm](https://cloud.githubusercontent.com/assets/564113/6050820/b48058ea-ac90-11e4-98d1-1595f4074e76.png)

**Comment by J3RN** [comment]
@tarebyte I think this was caused by the addition of the CoverMyMeds logo earlier. Will look into fixing it.

**Comment by J3RN** [comment]
Update: @tarebyte That should have been fixed by #63

**Comment by tiranno** [comment]
@J3RN I'll work on padding this weekend

**Comment by egladman** [comment]
We need to justify the text in mobile view.

**Comment by J3RN** [comment]
@egladman: Check out #65
