### ISSUE TITLE
cwdg.club?

### ISSUE THREAD

**Issue by J3RN** [CWDG/cwdg-website#43]
Hover is having a sale on .CLUB domains ($5). We should totally get cwdg.club.

Can I get a second? @tarebyte @Hardolaf @btmills @paultela

**Comment by J3RN** [comment]
We've decided this is too much effort

**Comment by arcdigital** [comment]
If you want this domain I'll hook you guys up

**Comment by J3RN** [comment]
@arcdigital That would be amazing, thanks!

**Comment by arcdigital** [comment]
Done...let me know what DNS records you need added.

**Comment by tarebyte** [comment]
Should just be the same records that we use for cwdgosu.org shouldn't it?

**Comment by arcdigital** [comment]
Added that, you'll have to add www.cwdg.club to the heroku app. (cwdg.club is not needed, as it redirects to www.cwdg.club)

**Comment by J3RN** [comment]
Will do.

**Comment by J3RN** [comment]
@arcdigital Heroku updated. www.cwdg.club DNS is working for me.

**Comment by J3RN** [comment]
Alright, since this is working, I think it's safe to close this.
