### ISSUE TITLE
Meeting Calendar

### ISSUE THREAD

**Issue by tarebyte** [CWDG/cwdg-website#49]
I see two ways this would work.

* Use Google Calendars to make the meeting and have it sync to the latest meeting.
* Build out the feature ourselves and run our own personal calendar.

What do you guys think?

/cc @CWDG/cwdg-website

**Comment by J3RN** [comment]
@tiranno This would be really nice to have. Please assign someone when you have a chance.

**Comment by Hardolaf** [comment]
@J3RN 
I need
- Google Calendar made for the club
- Edit access for the Calendar
- API Key, do not restrict domains until testing is done.

**Comment by J3RN** [comment]
@Hardolaf 
The first is done. The second comes with the third. The thing is - it looks like Google requires you to restrict domains. I can't seem to find a way around it.

I also assume the request will come server-side, not client-side, yes?

**Comment by J3RN** [comment]
UPDATE: I'm a herpaderp. Second is finished.
