### ISSUE TITLE
Cwdgosu.org not routing

### ISSUE THREAD

**Issue by J3RN** [CWDG/cwdg-website#68]
One of our domains, cwdgosu.org is routing to an "expired" page. This needs to be fixed.

@arcdigital Help?

**Comment by arcdigital** [comment]
My bad. I'll get this fixed tomorrow.

**Comment by J3RN** [comment]
@arcdigital Update?

**Comment by oslerw** [comment]
This also is breaking login via GitHub accounts, since it redirects to that domain.

**Comment by arcdigital** [comment]
It should be working again within the next 10 minutes.

**Comment by J3RN** [comment]
Fixed!
