### ISSUE TITLE
Rename "Tutorials" to "Blog"

### ISSUE THREAD

**Issue by J3RN** [CWDG/cwdg-website#82]
Currently, there is only one tutorial. My thought is to broaden what makes sense to be posted there, by renaming it "Blog." My inspiration is that while people might not be hot on writing newbie-focussed tutorials, folks might be interested in writing about their experiences working with framework X or technology Y. It could also serve as a place to post wordy updates about the club whenever I'm making changes.

Inspired (loosely) by [Giant Robots Smashing into Other Giant Robots](https://robots.thoughtbot.com/)

If anyone is opposed, I'd love to hear about it. Otherwise, I'll get to work on it.

**Comment by egladman** [comment]
I like your idea, definitly go for it.
